/**
 * Workflow Executor
 *
 * Walks a workflow state machine: evaluate current step, execute it,
 * evaluate transitions, move to next step. Repeats until a terminal
 * state ($done or $blocked) is reached.
 */

import type { Criterion, Session } from '../../shared/types.js'
import type { OrchestratorOptions, OrchestratorResult, NextAction } from '../runner/types.js'
import { RUNNER_CONFIG } from '../runner/types.js'
import type {
  WorkflowDefinition,
  WorkflowStep,
  Transition,
  TransitionCondition,
  AgentStep,
  SubAgentStep,
  ShellStep,
} from './types.js'
import { TERMINAL_DONE, TERMINAL_BLOCKED } from './types.js'
import { getEventStore, getCurrentContextWindowId } from '../events/index.js'
import { runBuilderTurn, TurnMetrics, createMessageStartEvent, type BuilderTurnOptions } from '../chat/orchestrator.js'
import { executeSubAgent } from '../sub-agents/manager.js'
import { createVerifierNudgeConfig } from '../sub-agents/verifier-helpers.js'
import { loadAllAgentsDefault, findAgentById } from '../agents/registry.js'
import { getToolRegistryForAgent } from '../tools/index.js'
import { computeSessionStats } from '../../shared/stats.js'
import { executeShellCommand } from './shell.js'
import { logger } from '../utils/logger.js'

// ============================================================================
// Template Variables
// ============================================================================

export interface TemplateContext {
  workdir: string
  reason: string
  /** @deprecated Use stepOutput.content instead */
  verifierFindings: string
  /** @deprecated Use stepOutput.stdout instead */
  previousStepOutput: string
  criteriaCount: number
  pendingCount: number
  summary: string
  criteriaList: string
  modifiedFiles: string
  stepOutput: Record<string, string>
}

/** Canonical list of template variables — single source of truth for resolveTemplate and the API. */
export const TEMPLATE_VARIABLES: Array<{ name: string; description: string }> = [
  { name: 'workdir', description: 'Working directory of the session' },
  { name: 'reason', description: 'Human-readable reason (e.g. "2 criteria remaining")' },
  { name: 'stepOutput', description: 'Structured output from the previous step (content, stdout, stderr, exitCode, etc.)' },
  { name: 'verifierFindings', description: '@deprecated Use stepOutput.content instead. Output from the last sub-agent step' },
  { name: 'previousStepOutput', description: '@deprecated Use stepOutput.stdout instead. Output from the last shell step' },
  { name: 'criteriaCount', description: 'Total number of criteria' },
  { name: 'pendingCount', description: 'Number of pending/failed criteria' },
  { name: 'summary', description: 'Session summary generated by planner' },
  { name: 'criteriaList', description: 'Formatted list of all criteria with status' },
  { name: 'modifiedFiles', description: 'List of modified files' },
]

export function formatCriteriaList(criteria: Criterion[]): string {
  if (criteria.length === 0) return '(none)'
  return criteria
    .map(c => {
      const status = c.status.type === 'passed' ? '[PASSED]'
        : c.status.type === 'completed' ? '[NEEDS VERIFICATION]'
        : c.status.type === 'failed' ? '[FAILED]'
        : '[NOT COMPLETED]'
      return `- **${c.id}** ${status}: ${c.description}`
    })
    .join('\n')
}

export function formatModifiedFiles(session: Session): string {
  const files = session.executionState?.modifiedFiles ?? []
  return files.length > 0 ? files.map(f => `- ${f}`).join('\n') : '(none)'
}

export function resolveTemplate(template: string, ctx: TemplateContext): string {
  let result = template
  for (const { name } of TEMPLATE_VARIABLES) {
    if (name === 'stepOutput' || name === 'verifierFindings' || name === 'previousStepOutput') continue
    const value = String(ctx[name as keyof TemplateContext])
    result = result.replace(new RegExp(`\\{\\{${name}\\}\\}`, 'g'), value)
  }
  result = result.replace(/\{\{stepOutput\.(\w+)\}\}/g, (_, key) => ctx.stepOutput[key] ?? '')
  result = result.replace(/\{\{verifierFindings\}\}/g, ctx.stepOutput['content'] ?? '')
  result = result.replace(/\{\{previousStepOutput\}\}/g, ctx.stepOutput['stdout'] ?? '')
  return result
}

// ============================================================================
// Transition Evaluation
// ============================================================================

export interface StepOutcome {
  result: string
  output: Record<string, string>
}

export function evaluateCondition(
  condition: TransitionCondition,
  criteria: Criterion[],
  stepOutcome: StepOutcome | null,
): boolean {
  switch (condition.type) {
    case 'all_criteria_passed':
      return criteria.length === 0 || criteria.every(c => c.status.type === 'passed')

    case 'all_criteria_completed_or_passed':
      return criteria.every(c => c.status.type === 'completed' || c.status.type === 'passed')

    case 'any_criteria_blocked':
      return criteria.some(c =>
        c.status.type === 'failed' &&
        c.attempts.filter(a => a.status === 'failed').length >= RUNNER_CONFIG.maxVerifyRetries
      )

    case 'has_pending_criteria':
      return criteria.some(c => c.status.type !== 'passed')

    case 'step_result':
      if (!stepOutcome) return false
      return stepOutcome.result === condition.result

    case 'always':
      return true
  }
}

export function evaluateTransitions(
  transitions: Transition[],
  criteria: Criterion[],
  stepOutcome: StepOutcome | null,
): string {
  for (const transition of transitions) {
    if (evaluateCondition(transition.when, criteria, stepOutcome)) {
      return transition.goto
    }
  }
  // No transition matched — treat as blocked
  return TERMINAL_BLOCKED
}

// ============================================================================
// Helper
// ============================================================================

function getCurrentWindowMessageOptions(sessionId: string): { contextWindowId: string } | undefined {
  const contextWindowId = getCurrentContextWindowId(sessionId)
  return contextWindowId ? { contextWindowId } : undefined
}

export function buildReason(criteria: Criterion[]): string {
  const remaining = criteria.filter(c => c.status.type !== 'passed')
  return `${remaining.length} criteria remaining`
}

// ============================================================================
// Executor
// ============================================================================

export async function executeWorkflow(
  workflow: WorkflowDefinition,
  options: OrchestratorOptions,
): Promise<OrchestratorResult> {
  const { sessionManager, sessionId, llmClient, signal, onMessage } = options
  const eventStore = getEventStore()
  const startTime = performance.now()
  let iterations = 0

  let currentStepId = workflow.entryStep
  let lastStepOutput: Record<string, string> = {}
  let isFirstBuilderEntry = true

  // Snapshot message count so we can compute workflow-scoped stats (not session-wide)
  const messagesBeforeWorkflow = sessionManager.requireSession(sessionId).messages.length

  const stepsById = new Map<string, WorkflowStep>()
  for (const step of workflow.steps) {
    stepsById.set(step.id, step)
  }

  logger.debug('Workflow executor starting', { sessionId, workflow: workflow.metadata.id })

  // Evaluate start condition if present
  if (workflow.startCondition && workflow.startCondition.type !== 'always') {
    const session = sessionManager.requireSession(sessionId)
    const criteria = session.criteria
    const conditionMet = evaluateCondition(
      workflow.startCondition as TransitionCondition,
      criteria,
      null,
    )
    if (!conditionMet) {
      logger.debug('Workflow start condition not met', { sessionId, condition: workflow.startCondition.type })
      return {
        finalAction: { type: 'BLOCKED', reason: `Start condition not met: ${workflow.startCondition.type}`, blockedCriteria: [] },
        iterations: 0,
        totalTime: (performance.now() - startTime) / 1000,
      }
    }
  }

  // Emit workflow-started marker into the feed
  const startMsgId = crypto.randomUUID()
  const startWindowOpts = getCurrentWindowMessageOptions(sessionId)
  eventStore.append(sessionId, createMessageStartEvent(startMsgId, 'user',
    JSON.stringify({ workflowName: workflow.metadata.name, workflowId: workflow.metadata.id, workflowColor: workflow.metadata.color }),
    { ...(startWindowOpts ?? {}), isSystemGenerated: true, messageKind: 'workflow-started' },
  ))
  eventStore.append(sessionId, { type: 'message.done', data: { messageId: startMsgId } })

  // Inject user-provided message after the workflow-started marker
  // Both go through EventStore so ordering is preserved
  if (options.userMessage) {
    sessionManager.addMessage(sessionId, {
      role: 'user',
      content: options.userMessage.content,
      ...(options.userMessage.attachments ? { attachments: options.userMessage.attachments } : {}),
    })
  }

  while (iterations < workflow.settings.maxIterations) {
    // Check abort
    if (signal?.aborted) {
      logger.debug('Workflow executor aborted', { sessionId, iterations })
      return {
        finalAction: { type: 'RUN_BUILDER', reason: 'Aborted' },
        iterations,
        totalTime: (performance.now() - startTime) / 1000,
      }
    }

    iterations++

    const step = stepsById.get(currentStepId)
    if (!step) {
      logger.error('Workflow step not found', { sessionId, stepId: currentStepId })
      return {
        finalAction: { type: 'BLOCKED', reason: `Step "${currentStepId}" not found in workflow`, blockedCriteria: [] },
        iterations,
        totalTime: (performance.now() - startTime) / 1000,
      }
    }

    const session = sessionManager.requireSession(sessionId)
    const currentWindowMessageOptions = getCurrentWindowMessageOptions(sessionId)
    const criteria = session.criteria

    // Build template context
    const templateCtx: TemplateContext = {
      workdir: session.workdir,
      reason: buildReason(criteria),
      verifierFindings: lastStepOutput['content'] ?? '',
      previousStepOutput: lastStepOutput['stdout'] ?? '',
      criteriaCount: criteria.length,
      pendingCount: criteria.filter(c => c.status.type !== 'passed').length,
      summary: session.summary ?? 'No summary available',
      criteriaList: formatCriteriaList(criteria),
      modifiedFiles: formatModifiedFiles(session),
      stepOutput: lastStepOutput,
    }

    // Set session phase
    sessionManager.setPhase(sessionId, step.phase as 'build' | 'verification' | 'blocked' | 'done')

    logger.debug('Workflow step executing', { sessionId, iteration: iterations, stepId: step.id, stepType: step.type })

    let stepOutcome: StepOutcome | null = null

    // Execute step
    switch (step.type) {
      case 'agent': {
        const agentStep = step as AgentStep
        const STEP_DONE_PROMPT = '\n\nOnce you\'re done, call step_done()'
        const STEP_DONE_NUDGE = 'You haven\'t called step_done(). If you haven\'t finished the task, continue and when you\'re finished call step_done()'

        // Build prompt content
        let promptContent: string | null = null
        let nudgeContent: string | null = null

        if (isFirstBuilderEntry && agentStep.prompt) {
          const resolvedPrompt = resolveTemplate(agentStep.prompt, templateCtx)
          promptContent = resolvedPrompt + STEP_DONE_PROMPT
          const promptMsgId = crypto.randomUUID()
          eventStore.append(sessionId, createMessageStartEvent(promptMsgId, 'user', promptContent, {
            ...(currentWindowMessageOptions ?? {}),
            isSystemGenerated: true,
            messageKind: 'auto-prompt',
            metadata: { type: 'workflow', name: 'Workflow', color: '#f59e0b' },
          }))
          eventStore.append(sessionId, { type: 'message.done', data: { messageId: promptMsgId } })
        } else if (!isFirstBuilderEntry) {
          // Build nudge: nudgePrompt first (if exists), then step_done nudge
          const parts: string[] = []
          if (agentStep.nudgePrompt) {
            const resolvedNudge = resolveTemplate(agentStep.nudgePrompt, templateCtx)
            parts.push(resolvedNudge)
          }
          parts.push(STEP_DONE_NUDGE)
          nudgeContent = parts.join('\n\n')
          
          const nudgeMsgId = crypto.randomUUID()
          eventStore.append(sessionId, createMessageStartEvent(nudgeMsgId, 'user', nudgeContent, {
            ...(currentWindowMessageOptions ?? {}),
            isSystemGenerated: true,
            messageKind: 'correction',
            metadata: { type: 'workflow', name: 'Workflow', color: '#f59e0b' },
          }))
          eventStore.append(sessionId, { type: 'message.done', data: { messageId: nudgeMsgId } })
        }

        const turnMetrics = new TurnMetrics()
        const agentResult = await runBuilderTurn({
          sessionManager,
          sessionId,
          llmClient,
          injectStepDone: true,
          ...(options.statsIdentity ? { statsIdentity: options.statsIdentity } : {}),
          ...(isFirstBuilderEntry && !agentStep.prompt && options.injectBuilderKickoff === true ? { injectBuilderKickoff: true } : {}),
          ...(signal ? { signal } : {}),
          ...(onMessage ? { onMessage } : {}),
        } as BuilderTurnOptions, turnMetrics)

        isFirstBuilderEntry = false
        const agentReturnValue = agentResult.returnValueResult ?? 'completed'
        const stepDoneCalled = agentResult.stepDoneCalled ?? false
        lastStepOutput = { ...(agentResult.returnValueContent ? { content: agentResult.returnValueContent } : {}), ...(agentResult.returnValueResult ? { result: agentResult.returnValueResult } : {}), stepDoneCalled: String(stepDoneCalled) }
        stepOutcome = { result: agentReturnValue, output: lastStepOutput }
        
        // If step_done was not called, loop back to continue the agent step
        if (!stepDoneCalled) {
          logger.debug('step_done not called, looping agent step', { sessionId, stepId: step.id, iteration: iterations })
          continue
        }
        
        break
      }

      case 'sub_agent': {
        const subStep = step as SubAgentStep
        const turnMetrics = new TurnMetrics()

        const promptTemplate = subStep.prompt ?? 'Perform your task.'
        const resolvedPrompt = resolveTemplate(promptTemplate, templateCtx)

        const allAgents = await loadAllAgentsDefault()
        const agentDef = findAgentById(subStep.subAgentType, allAgents)
        if (!agentDef) {
          logger.error('Sub-agent definition not found', { subAgentType: subStep.subAgentType })
          stepOutcome = { result: 'error', output: {} }
          break
        }

        const toolRegistry = getToolRegistryForAgent(agentDef)
        // Filter out step_done tool from sub-agents (it's workflow-executor-only)
        const filteredToolRegistry = {
          tools: toolRegistry.tools.filter(t => t.name !== 'step_done'),
          definitions: toolRegistry.definitions.filter(d => d.type === 'function' && d.function.name !== 'step_done'),
          execute: toolRegistry.execute,
        }

        const nudgeConfig = subStep.subAgentType === 'verifier' && !subStep.nudgePrompt
          ? createVerifierNudgeConfig()
          : undefined

        const result = await executeSubAgent({
          subAgentType: subStep.subAgentType,
          prompt: resolvedPrompt,
          sessionManager,
          sessionId,
          llmClient,
          toolRegistry: filteredToolRegistry,
          turnMetrics,
          statsIdentity: options.statsIdentity ?? { providerId: '', providerName: '', backend: 'unknown', model: llmClient.getModel() },
          ...(signal ? { signal } : {}),
          ...(onMessage ? { onMessage } : {}),
          nudgeConfig,
        })

        lastStepOutput = { content: result.content ?? '', ...(result.result ? { result: result.result } : {}) }
        stepOutcome = { result: result.result ?? 'success', output: lastStepOutput }
        break
      }

      case 'shell': {
        const shellStep = step as ShellStep
        const command = resolveTemplate(shellStep.command, templateCtx)
        const timeout = shellStep.timeout ?? 60_000
        const successCodes = shellStep.successExitCodes ?? [0]

        // Emit a message showing the shell command being run
        const shellMsgId = crypto.randomUUID()
        eventStore.append(sessionId, createMessageStartEvent(shellMsgId, 'user', `Running: \`${command}\``, {
          ...(currentWindowMessageOptions ?? {}),
          isSystemGenerated: true,
          messageKind: 'auto-prompt',
          metadata: { type: 'workflow', name: 'Workflow', color: '#f59e0b' },
        }))

        const result = await executeShellCommand(command, session.workdir, timeout, signal)

        const output = [result.stdout, result.stderr].filter(Boolean).join('\n').trim()
        lastStepOutput = { stdout: result.stdout ?? '', stderr: result.stderr ?? '', exitCode: String(result.exitCode) }

        // Append output as message content
        const outputContent = output
          ? `Exit code: ${result.exitCode}\n\`\`\`\n${output.slice(0, 10000)}\n\`\`\``
          : `Exit code: ${result.exitCode}`
        eventStore.append(sessionId, { type: 'message.done', data: { messageId: shellMsgId } })

        const outputMsgId = crypto.randomUUID()
        eventStore.append(sessionId, createMessageStartEvent(outputMsgId, 'user', outputContent, {
          ...(currentWindowMessageOptions ?? {}),
          isSystemGenerated: true,
          messageKind: 'correction',
        }))
        eventStore.append(sessionId, { type: 'message.done', data: { messageId: outputMsgId } })

        stepOutcome = { result: successCodes.includes(result.exitCode) ? 'success' : 'failure', output: lastStepOutput }
        break
      }
    }

    // Evaluate transitions
    const refreshedSession = sessionManager.requireSession(sessionId)
    const nextStepId = evaluateTransitions(
      step.transitions,
      refreshedSession.criteria,
      stepOutcome,
    )

    // Handle terminal states
    if (nextStepId === TERMINAL_DONE) {
      sessionManager.setPhase(sessionId, 'done')

      const totalTimeSeconds = Math.round((performance.now() - startTime) / 100) / 10
      const completedSession = sessionManager.requireSession(sessionId)
      // Only aggregate stats for messages created during this workflow run
      const workflowMessages = completedSession.messages.slice(messagesBeforeWorkflow)
      const workflowStats = computeSessionStats(workflowMessages)
      const totalToolCalls = workflowMessages.reduce(
        (sum, m) => sum + (m.toolCalls?.length ?? 0), 0
      )
      const taskCompletedData = {
        summary: null,
        iterations,
        totalTimeSeconds,
        totalToolCalls,
        totalTokensGenerated: workflowStats?.generationTokens ?? 0,
        avgGenerationSpeed: workflowStats?.avgGenerationSpeed ?? 0,
        responseCount: workflowStats?.responseCount ?? 0,
        llmCallCount: workflowStats?.llmCallCount ?? 0,
        criteria: [] as Array<{ id: string; description: string; status: string }>,
        workflowName: workflow.metadata.name,
        workflowId: workflow.metadata.id,
        ...(workflow.metadata.color ? { workflowColor: workflow.metadata.color } : {}),
      }
      eventStore.append(sessionId, { type: 'task.completed', data: taskCompletedData })

      const markerMsgId = crypto.randomUUID()
      eventStore.append(sessionId, createMessageStartEvent(markerMsgId, 'user', JSON.stringify(taskCompletedData), {
        ...(currentWindowMessageOptions ?? {}),
        isSystemGenerated: true,
        messageKind: 'task-completed',
      }))
      eventStore.append(sessionId, { type: 'message.done', data: { messageId: markerMsgId } })

      logger.debug('Workflow executor complete', { sessionId, iterations })
      const doneAction: NextAction = { type: 'DONE' }
      return {
        finalAction: doneAction,
        iterations,
        totalTime: totalTimeSeconds,
      }
    }

    if (nextStepId === TERMINAL_BLOCKED) {
      sessionManager.setPhase(sessionId, 'blocked')

      const blockedCriteria = refreshedSession.criteria
        .filter(c => c.status.type === 'failed' &&
          c.attempts.filter(a => a.status === 'failed').length >= RUNNER_CONFIG.maxVerifyRetries)
        .map(c => c.id)
      const reason = blockedCriteria.length > 0
        ? `Retry limit reached for: ${blockedCriteria.join(', ')}`
        : 'No matching transition'

      const blockedMsgId = crypto.randomUUID()
      eventStore.append(sessionId, createMessageStartEvent(blockedMsgId, 'user', `Runner blocked: ${reason}`, {
        ...(currentWindowMessageOptions ?? {}),
        isSystemGenerated: true,
        messageKind: 'correction',
        metadata: { type: 'workflow', name: 'Workflow', color: '#f59e0b' },
      }))
      eventStore.append(sessionId, { type: 'message.done', data: { messageId: blockedMsgId } })

      logger.warn('Workflow executor blocked', { sessionId, iterations, reason })
      const blockedAction: NextAction = { type: 'BLOCKED', reason, blockedCriteria }
      return {
        finalAction: blockedAction,
        iterations,
        totalTime: (performance.now() - startTime) / 1000,
      }
    }

    // Move to next step
    currentStepId = nextStepId
  }

  // Max iterations reached
  logger.warn('Workflow executor max iterations reached', { sessionId, iterations })
  return {
    finalAction: { type: 'BLOCKED', reason: `Max iterations (${workflow.settings.maxIterations}) reached`, blockedCriteria: [] },
    iterations,
    totalTime: (performance.now() - startTime) / 1000,
  }
}
