#!/bin/sh

script_dir=$(dirname "$0")/..
. "$script_dir/scripts/parallel-exit-on-failure.sh"

echo "  Running pre-push checks..."

parallel_exit_on_failure \
  "lint"      "npm run lint" \
  "typecheck" "npm run typecheck" \
  "format"    "npm run format" \
  "duplicate" "npm run duplicate" \
  "test"      "npm test"
